//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
/**
 * User model
 */
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Trip = $ModelResult<$Schema, "Trip">;
export type Location = $ModelResult<$Schema, "Location">;
export type TripUser = $ModelResult<$Schema, "TripUser">;
export type TripGroup = $ModelResult<$Schema, "TripGroup">;
export type TripGroupUser = $ModelResult<$Schema, "TripGroupUser">;
export type TripLegRsvp = $ModelResult<$Schema, "TripLegRsvp">;
export type TripLeg = $ModelResult<$Schema, "TripLeg">;
export type ExcursionRsvp = $ModelResult<$Schema, "ExcursionRsvp">;
export type Excursion = $ModelResult<$Schema, "Excursion">;
export const Role = $schema.enums.Role.values;
export type Role = (typeof Role)[keyof typeof Role];
export const TripRole = $schema.enums.TripRole.values;
export type TripRole = (typeof TripRole)[keyof typeof TripRole];
export const TripGroupRole = $schema.enums.TripGroupRole.values;
export type TripGroupRole = (typeof TripGroupRole)[keyof typeof TripGroupRole];
export const RsvpStatus = $schema.enums.RsvpStatus.values;
export type RsvpStatus = (typeof RsvpStatus)[keyof typeof RsvpStatus];
