//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@email" }, { name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(6) }, { name: "max", value: ExpressionUtils.literal(32) }] }] as readonly AttributeApplication[]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
                    default: false as FieldDefault
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                role: {
                    name: "role",
                    type: "Role",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("GUEST") }] }] as readonly AttributeApplication[],
                    default: "GUEST" as FieldDefault
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                tripUsers: {
                    name: "tripUsers",
                    type: "TripUser",
                    array: true,
                    relation: { opposite: "user" }
                },
                legRsvps: {
                    name: "legRsvps",
                    type: "TripLegRsvp",
                    array: true,
                    relation: { opposite: "user" }
                },
                excursionRsvps: {
                    name: "excursionRsvps",
                    type: "ExcursionRsvp",
                    array: true,
                    relation: { opposite: "user" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("user") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                token: {
                    name: "token",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("session") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                token: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                accountId: {
                    name: "accountId",
                    type: "String"
                },
                providerId: {
                    name: "providerId",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                accessToken: {
                    name: "accessToken",
                    type: "String",
                    optional: true
                },
                refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    optional: true
                },
                idToken: {
                    name: "idToken",
                    type: "String",
                    optional: true
                },
                accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("account") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Verification: {
            name: "Verification",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                identifier: {
                    name: "identifier",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("verification") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Trip: {
            name: "Trip",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                users: {
                    name: "users",
                    type: "TripUser",
                    array: true,
                    relation: { opposite: "trip" }
                },
                groups: {
                    name: "groups",
                    type: "TripGroup",
                    array: true,
                    relation: { opposite: "trip" }
                },
                legs: {
                    name: "legs",
                    type: "TripLeg",
                    array: true,
                    relation: { opposite: "trip" }
                },
                excursions: {
                    name: "excursions",
                    type: "Excursion",
                    array: true,
                    relation: { opposite: "trip" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        TripUser: {
            name: "TripUser",
            fields: {
                tripId: {
                    name: "tripId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "trip"
                    ] as readonly string[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                role: {
                    name: "role",
                    type: "TripRole"
                },
                trip: {
                    name: "trip",
                    type: "Trip",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "users", fields: ["tripId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "tripUsers", fields: ["userId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                groups: {
                    name: "groups",
                    type: "TripGroupUser",
                    array: true,
                    relation: { opposite: "tripUser" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("userId")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_user") }] }
            ] as readonly AttributeApplication[],
            idFields: ["tripId", "userId"],
            uniqueFields: {
                tripId_userId: { tripId: { type: "String" }, userId: { type: "String" } }
            }
        },
        TripGroup: {
            name: "TripGroup",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                tripId: {
                    name: "tripId",
                    type: "String",
                    foreignKeyFor: [
                        "trip"
                    ] as readonly string[]
                },
                trip: {
                    name: "trip",
                    type: "Trip",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "groups", fields: ["tripId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                tripGroupUsers: {
                    name: "tripGroupUsers",
                    type: "TripGroupUser",
                    array: true,
                    relation: { opposite: "tripGroup" }
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id"), ExpressionUtils.field("tripId")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_group") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                id_tripId: { id: { type: "String" }, tripId: { type: "String" } }
            }
        },
        TripGroupUser: {
            name: "TripGroupUser",
            fields: {
                role: {
                    name: "role",
                    type: "TripGroupRole"
                },
                tripId: {
                    name: "tripId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "tripGroup",
                        "tripUser"
                    ] as readonly string[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "tripUser"
                    ] as readonly string[]
                },
                tripGroupId: {
                    name: "tripGroupId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "tripGroup"
                    ] as readonly string[]
                },
                tripGroup: {
                    name: "tripGroup",
                    type: "TripGroup",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("tripGroupId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "tripGroupUsers", fields: ["tripId", "tripGroupId"], references: ["tripId", "id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                tripUser: {
                    name: "tripUser",
                    type: "TripUser",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("userId")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "groups", fields: ["tripId", "userId"], references: ["tripId", "userId"], onDelete: "Cascade", onUpdate: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripGroupId"), ExpressionUtils.field("tripId"), ExpressionUtils.field("userId")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_group_user") }] }
            ] as readonly AttributeApplication[],
            idFields: ["tripId", "userId", "tripGroupId"],
            uniqueFields: {
                tripGroupId_tripId_userId: { tripGroupId: { type: "String" }, tripId: { type: "String" }, userId: { type: "String" } }
            }
        },
        TripLegRsvp: {
            name: "TripLegRsvp",
            fields: {
                tripLegId: {
                    name: "tripLegId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "tripLeg"
                    ] as readonly string[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                status: {
                    name: "status",
                    type: "RsvpStatus"
                },
                notes: {
                    name: "notes",
                    type: "String",
                    optional: true
                },
                tripLeg: {
                    name: "tripLeg",
                    type: "TripLeg",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripLegId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "rsvps", fields: ["tripLegId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "legRsvps", fields: ["userId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripLegId"), ExpressionUtils.field("userId")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_leg_rsvp") }] }
            ] as readonly AttributeApplication[],
            idFields: ["tripLegId", "userId"],
            uniqueFields: {
                tripLegId_userId: { tripLegId: { type: "String" }, userId: { type: "String" } }
            }
        },
        TripLeg: {
            name: "TripLeg",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                startTime: {
                    name: "startTime",
                    type: "DateTime"
                },
                endTime: {
                    name: "endTime",
                    type: "DateTime"
                },
                tripId: {
                    name: "tripId",
                    type: "String",
                    foreignKeyFor: [
                        "trip"
                    ] as readonly string[]
                },
                trip: {
                    name: "trip",
                    type: "Trip",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "legs", fields: ["tripId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                excursions: {
                    name: "excursions",
                    type: "Excursion",
                    array: true,
                    relation: { opposite: "tripLeg" }
                },
                rsvps: {
                    name: "rsvps",
                    type: "TripLegRsvp",
                    array: true,
                    relation: { opposite: "tripLeg" }
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("name")]) }] },
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("id"), ExpressionUtils.field("tripId")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_leg") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                tripId_name: { tripId: { type: "String" }, name: { type: "String" } },
                id_tripId: { id: { type: "String" }, tripId: { type: "String" } }
            }
        },
        ExcursionRsvp: {
            name: "ExcursionRsvp",
            fields: {
                excursionId: {
                    name: "excursionId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "excursion"
                    ] as readonly string[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    id: true,
                    foreignKeyFor: [
                        "user"
                    ] as readonly string[]
                },
                status: {
                    name: "status",
                    type: "RsvpStatus"
                },
                notes: {
                    name: "notes",
                    type: "String",
                    optional: true
                },
                excursion: {
                    name: "excursion",
                    type: "Excursion",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("excursionId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "rsvps", fields: ["excursionId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "excursionRsvps", fields: ["userId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("excursionId"), ExpressionUtils.field("userId")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("excursion_rsvp") }] }
            ] as readonly AttributeApplication[],
            idFields: ["excursionId", "userId"],
            uniqueFields: {
                excursionId_userId: { excursionId: { type: "String" }, userId: { type: "String" } }
            }
        },
        Excursion: {
            name: "Excursion",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                startTime: {
                    name: "startTime",
                    type: "DateTime"
                },
                endTime: {
                    name: "endTime",
                    type: "DateTime"
                },
                tripId: {
                    name: "tripId",
                    type: "String",
                    foreignKeyFor: [
                        "trip",
                        "tripLeg"
                    ] as readonly string[]
                },
                trip: {
                    name: "trip",
                    type: "Trip",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "excursions", fields: ["tripId"], references: ["id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                tripLegId: {
                    name: "tripLegId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "tripLeg"
                    ] as readonly string[]
                },
                tripLeg: {
                    name: "tripLeg",
                    type: "TripLeg",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("tripLegId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("tripId"), ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }, { name: "onUpdate", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
                    relation: { opposite: "excursions", fields: ["tripId", "tripLegId"], references: ["tripId", "id"], onDelete: "Cascade", onUpdate: "Cascade" }
                },
                rsvps: {
                    name: "rsvps",
                    type: "ExcursionRsvp",
                    array: true,
                    relation: { opposite: "excursion" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("excursion") }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                ADMIN: "ADMIN",
                USER: "USER",
                GUEST: "GUEST"
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("role") }] }
            ] as readonly AttributeApplication[]
        },
        TripRole: {
            name: "TripRole",
            values: {
                OWNER: "OWNER",
                CONTRIBUTOR: "CONTRIBUTOR",
                VIEWER: "VIEWER",
                SPECTATOR: "SPECTATOR"
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_role") }] }
            ] as readonly AttributeApplication[]
        },
        TripGroupRole: {
            name: "TripGroupRole",
            values: {
                OWNER: "OWNER",
                CONTRIBUTOR: "CONTRIBUTOR",
                VIEWER: "VIEWER"
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("trip_group_role") }] }
            ] as readonly AttributeApplication[]
        },
        RsvpStatus: {
            name: "RsvpStatus",
            values: {
                ACCEPTED: "ACCEPTED",
                DECLINED: "DECLINED",
                MAYBE: "MAYBE"
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("rsvp_status") }] }
            ] as readonly AttributeApplication[]
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
